<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpcServer.proto

namespace RpcServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rpcServer.BattleGroupInfo</code>
 */
class BattleGroupInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ownerAddress = 1;</code>
     */
    private $ownerAddress = '';
    /**
     * Generated from protobuf field <code>uint64 id = 2;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>repeated uint64 cards = 3;</code>
     */
    private $cards;

    public function __construct() {
        \GPBMetadata\RpcServer::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string ownerAddress = 1;</code>
     * @return string
     */
    public function getOwnerAddress()
    {
        return $this->ownerAddress;
    }

    /**
     * Generated from protobuf field <code>string ownerAddress = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOwnerAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->ownerAddress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 2;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 cards = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCards()
    {
        return $this->cards;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 cards = 3;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCards($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->cards = $arr;

        return $this;
    }

}

