<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpcServer.proto

namespace RpcServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rpcServer.BattleInfoReply</code>
 */
class BattleInfoReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .rpcServer.BattleInfo battles = 1;</code>
     */
    private $battles;

    public function __construct() {
        \GPBMetadata\RpcServer::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .rpcServer.BattleInfo battles = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBattles()
    {
        return $this->battles;
    }

    /**
     * Generated from protobuf field <code>repeated .rpcServer.BattleInfo battles = 1;</code>
     * @param \RpcServer\BattleInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBattles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \RpcServer\BattleInfo::class);
        $this->battles = $arr;

        return $this;
    }

}

