<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpcServer.proto

namespace RpcServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rpcServer.BattleInfo</code>
 */
class BattleInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>uint64 winnerGroupId = 2;</code>
     */
    private $winnerGroupId = 0;
    /**
     * Generated from protobuf field <code>uint64 loserGroupId = 3;</code>
     */
    private $loserGroupId = 0;

    public function __construct() {
        \GPBMetadata\RpcServer::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 winnerGroupId = 2;</code>
     * @return int|string
     */
    public function getWinnerGroupId()
    {
        return $this->winnerGroupId;
    }

    /**
     * Generated from protobuf field <code>uint64 winnerGroupId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWinnerGroupId($var)
    {
        GPBUtil::checkUint64($var);
        $this->winnerGroupId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 loserGroupId = 3;</code>
     * @return int|string
     */
    public function getLoserGroupId()
    {
        return $this->loserGroupId;
    }

    /**
     * Generated from protobuf field <code>uint64 loserGroupId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLoserGroupId($var)
    {
        GPBUtil::checkUint64($var);
        $this->loserGroupId = $var;

        return $this;
    }

}

