<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpcServer.proto

namespace RpcServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rpcServer.CardsReply</code>
 */
class CardsReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 creationTime = 1;</code>
     */
    private $creationTime = 0;
    /**
     * Generated from protobuf field <code>uint64 battleCooldownEnd = 2;</code>
     */
    private $battleCooldownEnd = 0;
    /**
     * Generated from protobuf field <code>uint32 creationBattleID = 3;</code>
     */
    private $creationBattleID = 0;
    /**
     * Generated from protobuf field <code>uint32 currentBattleID = 4;</code>
     */
    private $currentBattleID = 0;
    /**
     * Generated from protobuf field <code>string attributes = 5;</code>
     */
    private $attributes = '';

    public function __construct() {
        \GPBMetadata\RpcServer::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint64 creationTime = 1;</code>
     * @return int|string
     */
    public function getCreationTime()
    {
        return $this->creationTime;
    }

    /**
     * Generated from protobuf field <code>uint64 creationTime = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreationTime($var)
    {
        GPBUtil::checkUint64($var);
        $this->creationTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 battleCooldownEnd = 2;</code>
     * @return int|string
     */
    public function getBattleCooldownEnd()
    {
        return $this->battleCooldownEnd;
    }

    /**
     * Generated from protobuf field <code>uint64 battleCooldownEnd = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBattleCooldownEnd($var)
    {
        GPBUtil::checkUint64($var);
        $this->battleCooldownEnd = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 creationBattleID = 3;</code>
     * @return int
     */
    public function getCreationBattleID()
    {
        return $this->creationBattleID;
    }

    /**
     * Generated from protobuf field <code>uint32 creationBattleID = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCreationBattleID($var)
    {
        GPBUtil::checkUint32($var);
        $this->creationBattleID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 currentBattleID = 4;</code>
     * @return int
     */
    public function getCurrentBattleID()
    {
        return $this->currentBattleID;
    }

    /**
     * Generated from protobuf field <code>uint32 currentBattleID = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrentBattleID($var)
    {
        GPBUtil::checkUint32($var);
        $this->currentBattleID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string attributes = 5;</code>
     * @return string
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * Generated from protobuf field <code>string attributes = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAttributes($var)
    {
        GPBUtil::checkString($var, True);
        $this->attributes = $var;

        return $this;
    }

}

