<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpcServer.proto

namespace RpcServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rpcServer.CardInfo</code>
 */
class CardInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ownerAddress = 1;</code>
     */
    private $ownerAddress = '';
    /**
     * Generated from protobuf field <code>uint64 id = 2;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>uint64 creationBattleId = 3;</code>
     */
    private $creationBattleId = 0;
    /**
     * Generated from protobuf field <code>uint64 attributes = 4;</code>
     */
    private $attributes = 0;

    public function __construct() {
        \GPBMetadata\RpcServer::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string ownerAddress = 1;</code>
     * @return string
     */
    public function getOwnerAddress()
    {
        return $this->ownerAddress;
    }

    /**
     * Generated from protobuf field <code>string ownerAddress = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOwnerAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->ownerAddress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 2;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 creationBattleId = 3;</code>
     * @return int|string
     */
    public function getCreationBattleId()
    {
        return $this->creationBattleId;
    }

    /**
     * Generated from protobuf field <code>uint64 creationBattleId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreationBattleId($var)
    {
        GPBUtil::checkUint64($var);
        $this->creationBattleId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 attributes = 4;</code>
     * @return int|string
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * Generated from protobuf field <code>uint64 attributes = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAttributes($var)
    {
        GPBUtil::checkUint64($var);
        $this->attributes = $var;

        return $this;
    }

}

