<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpcServer.proto

namespace RpcServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rpcServer.ContractAddresses</code>
 */
class ContractAddresses extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .rpcServer.ContractAddress items = 1;</code>
     */
    private $items;

    public function __construct() {
        \GPBMetadata\RpcServer::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .rpcServer.ContractAddress items = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .rpcServer.ContractAddress items = 1;</code>
     * @param \RpcServer\ContractAddress[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \RpcServer\ContractAddress::class);
        $this->items = $arr;

        return $this;
    }

}

