<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpcServer.proto

namespace RpcServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rpcServer.CreateCardRequest</code>
 */
class CreateCardRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ownerAddress = 1;</code>
     */
    private $ownerAddress = '';
    /**
     * Generated from protobuf field <code>.rpcServer.CoreContractAddress coreAddress = 2;</code>
     */
    private $coreAddress = null;

    public function __construct() {
        \GPBMetadata\RpcServer::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string ownerAddress = 1;</code>
     * @return string
     */
    public function getOwnerAddress()
    {
        return $this->ownerAddress;
    }

    /**
     * Generated from protobuf field <code>string ownerAddress = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOwnerAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->ownerAddress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.rpcServer.CoreContractAddress coreAddress = 2;</code>
     * @return \RpcServer\CoreContractAddress
     */
    public function getCoreAddress()
    {
        return $this->coreAddress;
    }

    /**
     * Generated from protobuf field <code>.rpcServer.CoreContractAddress coreAddress = 2;</code>
     * @param \RpcServer\CoreContractAddress $var
     * @return $this
     */
    public function setCoreAddress($var)
    {
        GPBUtil::checkMessage($var, \RpcServer\CoreContractAddress::class);
        $this->coreAddress = $var;

        return $this;
    }

}

