<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpcServer.proto

namespace RpcServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rpcServer.ECRecoverRequest</code>
 */
class ECRecoverRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string address = 1;</code>
     */
    private $address = '';
    /**
     * Generated from protobuf field <code>string signed = 2;</code>
     */
    private $signed = '';
    /**
     * Generated from protobuf field <code>string plaintext = 3;</code>
     */
    private $plaintext = '';

    public function __construct() {
        \GPBMetadata\RpcServer::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string address = 1;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string signed = 2;</code>
     * @return string
     */
    public function getSigned()
    {
        return $this->signed;
    }

    /**
     * Generated from protobuf field <code>string signed = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSigned($var)
    {
        GPBUtil::checkString($var, True);
        $this->signed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string plaintext = 3;</code>
     * @return string
     */
    public function getPlaintext()
    {
        return $this->plaintext;
    }

    /**
     * Generated from protobuf field <code>string plaintext = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPlaintext($var)
    {
        GPBUtil::checkString($var, True);
        $this->plaintext = $var;

        return $this;
    }

}

