language: php

php:
  - 7.1

before_script:
  - cp .env.travis .env
  - mysql -e 'create database laravel_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan jwt:secret
  - php artisan migrate --env=testing --no-interaction -vvv
  - php artisan db:seed --env=testing --no-interaction -vvv

script:
  - vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)