version: '3.2'

# Docker Services breakdown:
# db - mysql DB, used by backend
# redis - KV store, used by laravel queues
# nginx - webserver the backend, uses fpm as a backing
# fpm - is called by nginx to actually execute the php for the backendd
# frontend - runs React in dev mode with hot reloading 
# ethereum_proxy - glang gRPC server, is called by the backend, handles talking to eth network
# truffle_test - ephemeral container that runs the truffle (contract) tests
# eth_rpc - container that runs the ganache CLI, truffle_test uses this as a local eth node
# codegen_tools_proto - ephemeral, generates the golang + php stubs based on RpcServer.proto
# codegen_tools_abigen - ephemeral, generates the golang stubs based on solidity
# codegen_tools_abigen_js - ephemeral, generates the js ABI for React to consume based on solidity
# laravel_queue_worker - supervisord process that runs laravel queues
# laravel_cron_worker - supervisord process that runs laravel scheduler on cron
services:
  db:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cryptocards 
    ports:
      - "3307:3306" #expose 3306 on a nonstandard port so that it doesn't conflict with mysql on the host
  redis:
    image: redis:latest
    ports:
    - "6379:6379"
  nginx:
    image: nginx:latest
    ports:
        - "8728:8080"
    volumes:
        - ./backend:/var/www/laravel
    working_dir: /var/www/laravel
    links:
      - fpm
    volumes:
      - ./backend/vhost-docker.conf:/etc/nginx/conf.d/laravel.conf
  laravel_queue_worker:
    env_file: ./backend/.env.docker
    build: ./tools/php-queue-worker
    volumes:
      - ./backend/:/var/www/laravel
    links:
      - db 
      - redis
      - ethereum_proxy 
  laravel_cron_worker:
    env_file: ./backend/.env.docker
    build: ./tools/php-cron-worker
    volumes:
      - ./backend/:/var/www/laravel
    links:
      - db 
      - redis
      - ethereum_proxy 

  fpm:  
     build: ./backend
     ports:
         - "9000:9000"
     links: 
         - db
         - redis
         - ethereum_proxy
     volumes:
         - ./backend/:/var/www/laravel
     working_dir: /var/www/laravel
     env_file: ./backend/.env.docker
  frontend:
    build: ./frontend
    volumes:
        - { type: bind, source: ./frontend, target: /app }
    environment:
      REACT_APP_API_BASE_URL: http://localhost:8728/v1
      REACT_APP_SITE_URL: http://localhost:5000
      PORT: 3000
    ports:
      - "5000:3000" #expose 3000 via 5000
      - "35729:35729" #for hot reloading

  ethereum_proxy:
    build: ./ethereum_proxy 
    volumes: 
      - { type: bind, source: ./ethereum_proxy, target: /ethereum_proxy }
    environment:
      PORT: 50051
      RPC_HOST: eth_rpc
      RPC_PORT: 8545
    links: 
       - eth_rpc

  truffle_test:
    build: ./eth_contracts
    volumes:  
      - ./eth_contracts:/app
    environment:
      RPC_HOST: eth_rpc
      RPC_PORT: 8545
    links:
      - eth_rpc
      - nginx

  eth_rpc: 
    image: nicky/ganache-cli
    command: --deterministic --networkId 999999
    ports:
      - "8545:8545"

  codegen_tools_proto:
    build: ./tools/proto
    volumes: 
      - { type: bind, source: ./backend, target: /backend }
      - { type: bind, source: ./ethereum_proxy, target: /ethereum_proxy }
      - { type: bind, source: ./tools, target: /tools }

  codegen_tools_abigen:
    build: ./tools/abigen
    volumes:
      - { type: bind, source: ./eth_contracts, target: /eth_contracts}
      - { type: bind, source: ./ethereum_proxy, target: /ethereum_proxy }
      - { type: bind, source: ./tools, target: /tools }

  codegen_tools_abigen_js:
    build: ./tools/abigen_js
    volumes:
      - { type: bind, source: ./eth_contracts, target: /eth_contracts}
      - { type: bind, source: ./frontend, target: /frontend }
      - { type: bind, source: ./tools, target: /tools }

