version: 2
jobs:
  build_frontend:
    docker: 
      - image: node:9.3.0
    working_directory: ~/cryptocards
    steps:
      - checkout
      - run: cd frontend && yarn install
      - run: cd frontend && yarn run build-css
      - run: cd frontend && yarn test
workflows:
  version: 2
  build_fullstack:
    jobs:
      - build_frontend
