<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpcServer.proto

namespace GPBMetadata;

class RpcServer
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aaa010a0f7270635365727665722e70726f746f12097270635365727665" .
            "72221c0a0c426c616e6b52657175657374120c0a046e616d651801200128" .
            "09221d0a0a426c616e6b5265706c79120f0a076d65737361676518012001" .
            "280932470a0747726565746572123c0a08476574426c616e6b12172e7270" .
            "635365727665722e426c616e6b526571756573741a152e72706353657276" .
            "65722e426c616e6b5265706c792200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

