// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpcServer.proto

/*
Package rpcServer is a generated protocol buffer package.

It is generated from these files:
	rpcServer.proto

It has these top-level messages:
	BlankRequest
	BlankReply
*/
package rpcServer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlankRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *BlankRequest) Reset()                    { *m = BlankRequest{} }
func (m *BlankRequest) String() string            { return proto.CompactTextString(m) }
func (*BlankRequest) ProtoMessage()               {}
func (*BlankRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BlankRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BlankReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *BlankReply) Reset()                    { *m = BlankReply{} }
func (m *BlankReply) String() string            { return proto.CompactTextString(m) }
func (*BlankReply) ProtoMessage()               {}
func (*BlankReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BlankReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*BlankRequest)(nil), "rpcServer.BlankRequest")
	proto.RegisterType((*BlankReply)(nil), "rpcServer.BlankReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	GetBlank(ctx context.Context, in *BlankRequest, opts ...grpc.CallOption) (*BlankReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) GetBlank(ctx context.Context, in *BlankRequest, opts ...grpc.CallOption) (*BlankReply, error) {
	out := new(BlankReply)
	err := grpc.Invoke(ctx, "/rpcServer.Greeter/GetBlank", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	GetBlank(context.Context, *BlankRequest) (*BlankReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_GetBlank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetBlank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcServer.Greeter/GetBlank",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetBlank(ctx, req.(*BlankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpcServer.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlank",
			Handler:    _Greeter_GetBlank_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcServer.proto",
}

func init() { proto.RegisterFile("rpcServer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x2a, 0x48, 0x0e,
	0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0x29, 0x71, 0xf1, 0x38, 0xe5, 0x24, 0xe6, 0x65, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08,
	0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9,
	0x4a, 0x6a, 0x5c, 0x5c, 0x50, 0x35, 0x05, 0x39, 0x95, 0x42, 0x12, 0x5c, 0xec, 0xb9, 0xa9, 0xc5,
	0xc5, 0x89, 0xe9, 0x30, 0x45, 0x30, 0xae, 0x91, 0x3b, 0x17, 0xbb, 0x7b, 0x51, 0x6a, 0x6a, 0x49,
	0x6a, 0x91, 0x90, 0x0d, 0x17, 0x87, 0x7b, 0x6a, 0x09, 0x58, 0x97, 0x90, 0xb8, 0x1e, 0xc2, 0x7e,
	0x64, 0xbb, 0xa4, 0x44, 0x31, 0x25, 0x0a, 0x72, 0x2a, 0x95, 0x18, 0x92, 0xd8, 0xc0, 0xce, 0x34,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xee, 0x67, 0x7e, 0x47, 0xb9, 0x00, 0x00, 0x00,
}
