// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpcServer.proto

/*
Package rpcServer is a generated protocol buffer package.

It is generated from these files:
	rpcServer.proto

It has these top-level messages:
	BlankRequest
	BlankReply
	CardsRequest
	CardsReply
	CoreContractAddress
	BattleGroupInfo
	BattleGroupInfoReply
	BattleGroupInfoRequest
	ECRecoverRequest
	ECRecoverReply
*/
package rpcServer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlankRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *BlankRequest) Reset()                    { *m = BlankRequest{} }
func (m *BlankRequest) String() string            { return proto.CompactTextString(m) }
func (*BlankRequest) ProtoMessage()               {}
func (*BlankRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BlankRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BlankReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *BlankReply) Reset()                    { *m = BlankReply{} }
func (m *BlankReply) String() string            { return proto.CompactTextString(m) }
func (*BlankReply) ProtoMessage()               {}
func (*BlankReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BlankReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CardsRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *CardsRequest) Reset()                    { *m = CardsRequest{} }
func (m *CardsRequest) String() string            { return proto.CompactTextString(m) }
func (*CardsRequest) ProtoMessage()               {}
func (*CardsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CardsRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type CardsReply struct {
	CreationTime      uint64 `protobuf:"varint,1,opt,name=creationTime" json:"creationTime,omitempty"`
	BattleCooldownEnd uint64 `protobuf:"varint,2,opt,name=battleCooldownEnd" json:"battleCooldownEnd,omitempty"`
	CreationBattleID  uint32 `protobuf:"varint,3,opt,name=creationBattleID" json:"creationBattleID,omitempty"`
	CurrentBattleID   uint32 `protobuf:"varint,4,opt,name=currentBattleID" json:"currentBattleID,omitempty"`
	Attributes        string `protobuf:"bytes,5,opt,name=attributes" json:"attributes,omitempty"`
}

func (m *CardsReply) Reset()                    { *m = CardsReply{} }
func (m *CardsReply) String() string            { return proto.CompactTextString(m) }
func (*CardsReply) ProtoMessage()               {}
func (*CardsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CardsReply) GetCreationTime() uint64 {
	if m != nil {
		return m.CreationTime
	}
	return 0
}

func (m *CardsReply) GetBattleCooldownEnd() uint64 {
	if m != nil {
		return m.BattleCooldownEnd
	}
	return 0
}

func (m *CardsReply) GetCreationBattleID() uint32 {
	if m != nil {
		return m.CreationBattleID
	}
	return 0
}

func (m *CardsReply) GetCurrentBattleID() uint32 {
	if m != nil {
		return m.CurrentBattleID
	}
	return 0
}

func (m *CardsReply) GetAttributes() string {
	if m != nil {
		return m.Attributes
	}
	return ""
}

type CoreContractAddress struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *CoreContractAddress) Reset()                    { *m = CoreContractAddress{} }
func (m *CoreContractAddress) String() string            { return proto.CompactTextString(m) }
func (*CoreContractAddress) ProtoMessage()               {}
func (*CoreContractAddress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CoreContractAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type BattleGroupInfo struct {
	OwnerAddress string   `protobuf:"bytes,1,opt,name=ownerAddress" json:"ownerAddress,omitempty"`
	Id           uint64   `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Cards        []uint64 `protobuf:"varint,3,rep,packed,name=cards" json:"cards,omitempty"`
}

func (m *BattleGroupInfo) Reset()                    { *m = BattleGroupInfo{} }
func (m *BattleGroupInfo) String() string            { return proto.CompactTextString(m) }
func (*BattleGroupInfo) ProtoMessage()               {}
func (*BattleGroupInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BattleGroupInfo) GetOwnerAddress() string {
	if m != nil {
		return m.OwnerAddress
	}
	return ""
}

func (m *BattleGroupInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BattleGroupInfo) GetCards() []uint64 {
	if m != nil {
		return m.Cards
	}
	return nil
}

type BattleGroupInfoReply struct {
	Items []*BattleGroupInfo `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *BattleGroupInfoReply) Reset()                    { *m = BattleGroupInfoReply{} }
func (m *BattleGroupInfoReply) String() string            { return proto.CompactTextString(m) }
func (*BattleGroupInfoReply) ProtoMessage()               {}
func (*BattleGroupInfoReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *BattleGroupInfoReply) GetItems() []*BattleGroupInfo {
	if m != nil {
		return m.Items
	}
	return nil
}

type BattleGroupInfoRequest struct {
	Contract *CoreContractAddress `protobuf:"bytes,1,opt,name=contract" json:"contract,omitempty"`
}

func (m *BattleGroupInfoRequest) Reset()                    { *m = BattleGroupInfoRequest{} }
func (m *BattleGroupInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*BattleGroupInfoRequest) ProtoMessage()               {}
func (*BattleGroupInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *BattleGroupInfoRequest) GetContract() *CoreContractAddress {
	if m != nil {
		return m.Contract
	}
	return nil
}

type ECRecoverRequest struct {
	Address   string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Signed    string `protobuf:"bytes,2,opt,name=signed" json:"signed,omitempty"`
	Plaintext string `protobuf:"bytes,3,opt,name=plaintext" json:"plaintext,omitempty"`
}

func (m *ECRecoverRequest) Reset()                    { *m = ECRecoverRequest{} }
func (m *ECRecoverRequest) String() string            { return proto.CompactTextString(m) }
func (*ECRecoverRequest) ProtoMessage()               {}
func (*ECRecoverRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ECRecoverRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ECRecoverRequest) GetSigned() string {
	if m != nil {
		return m.Signed
	}
	return ""
}

func (m *ECRecoverRequest) GetPlaintext() string {
	if m != nil {
		return m.Plaintext
	}
	return ""
}

type ECRecoverReply struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *ECRecoverReply) Reset()                    { *m = ECRecoverReply{} }
func (m *ECRecoverReply) String() string            { return proto.CompactTextString(m) }
func (*ECRecoverReply) ProtoMessage()               {}
func (*ECRecoverReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ECRecoverReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*BlankRequest)(nil), "rpcServer.BlankRequest")
	proto.RegisterType((*BlankReply)(nil), "rpcServer.BlankReply")
	proto.RegisterType((*CardsRequest)(nil), "rpcServer.CardsRequest")
	proto.RegisterType((*CardsReply)(nil), "rpcServer.CardsReply")
	proto.RegisterType((*CoreContractAddress)(nil), "rpcServer.CoreContractAddress")
	proto.RegisterType((*BattleGroupInfo)(nil), "rpcServer.BattleGroupInfo")
	proto.RegisterType((*BattleGroupInfoReply)(nil), "rpcServer.BattleGroupInfoReply")
	proto.RegisterType((*BattleGroupInfoRequest)(nil), "rpcServer.BattleGroupInfoRequest")
	proto.RegisterType((*ECRecoverRequest)(nil), "rpcServer.ECRecoverRequest")
	proto.RegisterType((*ECRecoverReply)(nil), "rpcServer.ECRecoverReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	GetBlank(ctx context.Context, in *BlankRequest, opts ...grpc.CallOption) (*BlankReply, error)
	GetCardsByOwner(ctx context.Context, in *CardsRequest, opts ...grpc.CallOption) (*CardsReply, error)
	RequestBattleGroupInfo(ctx context.Context, in *BattleGroupInfoRequest, opts ...grpc.CallOption) (*BattleGroupInfoReply, error)
	PerformECRecover(ctx context.Context, in *ECRecoverRequest, opts ...grpc.CallOption) (*ECRecoverReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) GetBlank(ctx context.Context, in *BlankRequest, opts ...grpc.CallOption) (*BlankReply, error) {
	out := new(BlankReply)
	err := grpc.Invoke(ctx, "/rpcServer.Greeter/GetBlank", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetCardsByOwner(ctx context.Context, in *CardsRequest, opts ...grpc.CallOption) (*CardsReply, error) {
	out := new(CardsReply)
	err := grpc.Invoke(ctx, "/rpcServer.Greeter/GetCardsByOwner", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) RequestBattleGroupInfo(ctx context.Context, in *BattleGroupInfoRequest, opts ...grpc.CallOption) (*BattleGroupInfoReply, error) {
	out := new(BattleGroupInfoReply)
	err := grpc.Invoke(ctx, "/rpcServer.Greeter/RequestBattleGroupInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) PerformECRecover(ctx context.Context, in *ECRecoverRequest, opts ...grpc.CallOption) (*ECRecoverReply, error) {
	out := new(ECRecoverReply)
	err := grpc.Invoke(ctx, "/rpcServer.Greeter/PerformECRecover", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	GetBlank(context.Context, *BlankRequest) (*BlankReply, error)
	GetCardsByOwner(context.Context, *CardsRequest) (*CardsReply, error)
	RequestBattleGroupInfo(context.Context, *BattleGroupInfoRequest) (*BattleGroupInfoReply, error)
	PerformECRecover(context.Context, *ECRecoverRequest) (*ECRecoverReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_GetBlank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetBlank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcServer.Greeter/GetBlank",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetBlank(ctx, req.(*BlankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetCardsByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetCardsByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcServer.Greeter/GetCardsByOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetCardsByOwner(ctx, req.(*CardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_RequestBattleGroupInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BattleGroupInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).RequestBattleGroupInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcServer.Greeter/RequestBattleGroupInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).RequestBattleGroupInfo(ctx, req.(*BattleGroupInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_PerformECRecover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ECRecoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).PerformECRecover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcServer.Greeter/PerformECRecover",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).PerformECRecover(ctx, req.(*ECRecoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpcServer.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlank",
			Handler:    _Greeter_GetBlank_Handler,
		},
		{
			MethodName: "GetCardsByOwner",
			Handler:    _Greeter_GetCardsByOwner_Handler,
		},
		{
			MethodName: "RequestBattleGroupInfo",
			Handler:    _Greeter_RequestBattleGroupInfo_Handler,
		},
		{
			MethodName: "PerformECRecover",
			Handler:    _Greeter_PerformECRecover_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcServer.proto",
}

func init() { proto.RegisterFile("rpcServer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 509 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x5d, 0xbf, 0xd6, 0xe6, 0xae, 0xac, 0xc5, 0x8c, 0x12, 0x0a, 0x1a, 0xc5, 0x0f, 0x28, 0x9a,
	0xd0, 0x40, 0xe5, 0x0d, 0xf1, 0xb2, 0x86, 0xa9, 0x4c, 0x42, 0x02, 0x99, 0xbd, 0x21, 0x21, 0xb9,
	0xc9, 0xdd, 0x14, 0x91, 0xda, 0xc1, 0x71, 0x36, 0xfa, 0xd7, 0xf8, 0x1d, 0xfc, 0x20, 0x14, 0x27,
	0x69, 0x93, 0xb4, 0x2a, 0x6f, 0xbd, 0xe7, 0x1e, 0x1f, 0xf7, 0x9e, 0x7b, 0x1c, 0x18, 0xa8, 0xc8,
	0xfb, 0x86, 0xea, 0x0e, 0xd5, 0x79, 0xa4, 0xa4, 0x96, 0xc4, 0x5a, 0x03, 0x94, 0x42, 0x7f, 0x16,
	0x72, 0xf1, 0x93, 0xe1, 0xaf, 0x04, 0x63, 0x4d, 0x08, 0xb4, 0x05, 0x5f, 0xa2, 0xdd, 0x98, 0x34,
	0x1c, 0x8b, 0x99, 0xdf, 0xf4, 0x15, 0x40, 0xce, 0x89, 0xc2, 0x15, 0xb1, 0xa1, 0xbb, 0xc4, 0x38,
	0xe6, 0xb7, 0x05, 0xa9, 0x28, 0xa9, 0x03, 0x7d, 0x97, 0x2b, 0x3f, 0x2e, 0xb4, 0x6c, 0xe8, 0x72,
	0xdf, 0x57, 0x18, 0xc7, 0x05, 0x33, 0x2f, 0xe9, 0xdf, 0x06, 0x40, 0x4e, 0x4d, 0x25, 0x29, 0xf4,
	0x3d, 0x85, 0x5c, 0x07, 0x52, 0x5c, 0x07, 0xf9, 0xe5, 0x6d, 0x56, 0xc1, 0xc8, 0x6b, 0x78, 0xb8,
	0xe0, 0x5a, 0x87, 0xe8, 0x4a, 0x19, 0xfa, 0xf2, 0x5e, 0x5c, 0x0a, 0xdf, 0x6e, 0x1a, 0xe2, 0x76,
	0x83, 0x9c, 0xc1, 0xb0, 0x38, 0x3d, 0x33, 0xcd, 0xab, 0x8f, 0x76, 0x6b, 0xd2, 0x70, 0x1e, 0xb0,
	0x2d, 0x9c, 0x38, 0x30, 0xf0, 0x12, 0xa5, 0x50, 0xe8, 0x35, 0xb5, 0x6d, 0xa8, 0x75, 0x98, 0x9c,
	0x02, 0x70, 0xad, 0x55, 0xb0, 0x48, 0x34, 0xc6, 0x76, 0xc7, 0xcc, 0x54, 0x42, 0xe8, 0x1b, 0x78,
	0xe4, 0x4a, 0x85, 0xae, 0x14, 0x5a, 0x71, 0x4f, 0x5f, 0x64, 0xd3, 0xee, 0xf1, 0xe1, 0x3b, 0x0c,
	0x32, 0xf1, 0xb9, 0x92, 0x49, 0x74, 0x25, 0x6e, 0x64, 0xea, 0x85, 0xbc, 0x17, 0xa8, 0x2e, 0x2a,
	0x27, 0x2a, 0x18, 0x39, 0x86, 0x66, 0x50, 0x0c, 0xdf, 0x0c, 0x7c, 0x72, 0x02, 0x1d, 0x2f, 0x75,
	0xd3, 0x6e, 0x4d, 0x5a, 0x4e, 0x9b, 0x65, 0x05, 0xfd, 0x04, 0x27, 0x35, 0xf1, 0xcc, 0xed, 0xb7,
	0xd0, 0x09, 0x34, 0x2e, 0x53, 0xe9, 0x96, 0x73, 0x34, 0x1d, 0x9f, 0x6f, 0xe2, 0x51, 0xe7, 0x67,
	0x44, 0x7a, 0x0d, 0xa3, 0x2d, 0xa5, 0x6c, 0xc5, 0xef, 0xa1, 0xe7, 0xe5, 0xd3, 0x9a, 0x7f, 0x7a,
	0x34, 0x3d, 0x2d, 0xc9, 0xed, 0x30, 0x83, 0xad, 0xf9, 0x74, 0x01, 0xc3, 0x4b, 0x97, 0xa1, 0x27,
	0xef, 0x50, 0xfd, 0x37, 0x32, 0x64, 0x04, 0x87, 0x71, 0x70, 0x2b, 0x30, 0x9b, 0xdb, 0x62, 0x79,
	0x45, 0x9e, 0x83, 0x15, 0x85, 0x3c, 0x10, 0x1a, 0x7f, 0x6b, 0xb3, 0x62, 0x8b, 0x6d, 0x00, 0x7a,
	0x06, 0xc7, 0xa5, 0x3b, 0xf2, 0xf8, 0xc6, 0x89, 0xe7, 0x15, 0x37, 0xf4, 0x58, 0x51, 0x4e, 0xff,
	0x34, 0xa1, 0x3b, 0x57, 0x88, 0x1a, 0x15, 0xf9, 0x00, 0xbd, 0x39, 0x6a, 0x93, 0x7a, 0xf2, 0xa4,
	0x6c, 0x50, 0xe9, 0xad, 0x8c, 0x1f, 0x6f, 0x37, 0xa2, 0x70, 0x45, 0x0f, 0x88, 0x0b, 0x83, 0x39,
	0x6a, 0x13, 0xf0, 0xd9, 0xea, 0x4b, 0xba, 0xb9, 0x8a, 0x48, 0xf9, 0x91, 0x54, 0x44, 0x36, 0x4f,
	0x82, 0x1e, 0x90, 0x1f, 0x30, 0xca, 0x39, 0xf5, 0x88, 0xbc, 0xdc, 0xb3, 0xb1, 0x5c, 0xf5, 0xc5,
	0x3e, 0x4a, 0xa6, 0xff, 0x19, 0x86, 0x5f, 0x51, 0xdd, 0x48, 0xb5, 0x5c, 0x3b, 0x44, 0x9e, 0x95,
	0x8e, 0xd5, 0x77, 0x33, 0x7e, 0xba, 0xbb, 0x69, 0xd4, 0x16, 0x87, 0xe6, 0xcb, 0xf2, 0xee, 0x5f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xb4, 0xb7, 0xd5, 0x39, 0x6c, 0x04, 0x00, 0x00,
}
